source 'https://rubygems.org'

ruby '>= 3.2.2'

gem 'cocoapods', '~> 1.12'
gem 'fastlane'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval(File.read(plugins_path), binding) if File.exist?(plugins_path)
